AWSTemplateFormatVersion: 2010-09-09
Description:
  ec2 instes kurulacak
Resources:
  set of resources ssh. ve http açık olacak
Type: AWS::EC2::SecurityGroup
Properties: 
  GroupDescription: SSH+http
  SecurityGroupIngress: 
    - IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0  
  Tags: 
    - Key: Name 
      Value: ssh-http

Type: AWS::EC2::Instance
Properties:   
  ImageId: ami-0889a44b331db0194
  InstanceType: t2.micro
  KeyName: first-key-pair
  SecurityGroups: 
    - String
  Tags: 
    - Key: Name 
      Value: instesdatabase
  UserData: String
  